settings:
  title: 'Status Page'
  url: 'https://status.strueker.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: strueker-dev # unique identifier
    name: strueker.dev
    description: '' # default=empty
    url: 'https://strueker.dev/en/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

  - id: strueker-net
    name: strueker.net
    description: ''
    url: 'https://strueker.net'
    method: GET
    expectStatus: 200
    followRedirect: false

  - id: mail-strueker-net
    name: Strueker Mail System
    url: 'https://mail.strueker.net/'
    method: GET
    expectStatus: 200
    followRedirect: false
    
  - id: cloud-strueker-net
    name: Strueker Cloud
    url: 'https://cloud.strueker.net'
    method: GET
    expectStatus: 200
    followRedirect: true
    
  - id: bifrost-strueker-net
    name: Strueker Bastion
    url: 'https://bifrost.strueker.net'
    method: GET
    expectStatus: 200
    followRedirect: false
